### ISSUE TITLE
Options are unclear

### ISSUE THREAD

**Issue by VeldMuijz** [noyobo/gulp-compass-compile#3]
The documentation on this project is very short and incomplete.
What are the settings we set with the options object?

I noticed that when I didn't set `force: true` and didn't change my base.scss file it would fail to compile with an error like the one below:
    Error: Broken @import declaration of "variables" Broken @import declaration of "../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap"

Could you clarify what the options do?

**Comment by noyobo** [comment]
@VeldMuijz 
Thank you for your feedback;

`gulp-compass-compile` just use gulp of compass made a package, let me faster compile sass;
Specific use the document you can refer to http://compass-style.org/help/documentation/

You can post your directory structure, I can see where the problems lie;
I guess you need to specify the `import` directory, like this 
[test.js#117](https://github.com/noyobo/gulp-compass-compile/blob/master/test/test.js#L117)
